version: 0.0
os: linux
files:
  - source: helloworld.js
    destination: /usr/local/helloworld/
  - source: scripts/helloworld.conf
    destination: /etc/init/
  - source: conf/logrotate
    destination: /etc/logrotate.d/helloworld
  - source: node_modules
    destination: /usr/local/helloworld/node_modules
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 30
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 30
  ValidateService:
    - location: scripts/validate.sh
  AfterInstall:
    - location: scripts/setversion.sh
      timeout: 180
